layout_spectrum: 0.1626514
color:
  saturation: 0.1542045
  lightness: 0.4546376
  brandStrength: 1
  brandColors:
    - '#000000'
    - '#0F0F0F'
    - '#202020'
    - '#303030'
    - '#3D3D3D'
  rhythmicContrast: 0.3834798
typography_spectrum: 0.327957
name: Day Din
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2bd2f86b-832e-4857-a7b9-5e2fc3f83c04.png
